"""Initial tables

Revision ID: c667a029b5ef
Revises: 
Create Date: 2026-09-25 17:54:31.261416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c667a029b5ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('recommendation', sa.String(length=300), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_route_created', 'predictions', ['route_id', 'created_at'], unique=False)
    op.create_index('ix_prediction_vehicle_created', 'predictions', ['vehicle_id', 'created_at'], unique=False)
    op.create_table('processed_stream_messages',
    sa.Column('stream_id', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stream_id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('stop_id', sa.String(length=50), nullable=False),
    sa.Column('stop_name', sa.String(length=200), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_id', 'scheduled_arrival', name='uq_schedule_route_stop_arrival')
    )
    op.create_index('ix_schedule_route_arrival', 'schedules', ['route_id', 'scheduled_arrival'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('location_valid', sa.Boolean(), nullable=True),
    sa.Column('stop_id', sa.String(length=50), nullable=True),
    sa.Column('dwell_time_seconds', sa.Float(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_route_event_time', 'telemetry', ['route_id', 'event_time'], unique=False)
    op.create_index('ix_vehicle_event_time', 'telemetry', ['vehicle_id', 'event_time'], unique=False)
    op.create_table('vehicle_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('unit_id >= 0 AND unit_id <= 2147483647'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_index('ix_vehicle_routes_route_id', 'vehicle_routes', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_routes_route_id', table_name='vehicle_routes')
    op.drop_table('vehicle_routes')
    op.drop_index('ix_vehicle_event_time', table_name='telemetry')
    op.drop_index('ix_route_event_time', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index('ix_schedule_route_arrival', table_name='schedules')
    op.drop_table('schedules')
    op.drop_table('processed_stream_messages')
    op.drop_index('ix_prediction_vehicle_created', table_name='predictions')
    op.drop_index('ix_prediction_route_created', table_name='predictions')
    op.drop_table('predictions')
    # ### end Alembic commands ###
