"""add stop_crossings

Revision ID: b45d8d988f24
Revises: c7debc645ad6
Create Date: 2026-09-26 23:05:06.269655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45d8d988f24'
down_revision: Union[str, Sequence[str], None] = 'c7debc645ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stop_crossings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=True),
    sa.Column('stop_id', sa.String(length=50), nullable=False),
    sa.Column('planned_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delay_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stop_crossings_route', 'stop_crossings', ['route_id', 'actual_time'], unique=False)
    op.create_index('idx_stop_crossings_vehicle', 'stop_crossings', ['vehicle_id', 'actual_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stop_crossings_vehicle', table_name='stop_crossings')
    op.drop_index('idx_stop_crossings_route', table_name='stop_crossings')
    op.drop_table('stop_crossings')
    # ### end Alembic commands ###
